### ISSUE TITLE
Need those binary and config files

### ISSUE THREAD

**Issue by 570n3** [admredbeard/Hyperledger_Fabric_PoC#1]
Hello,

Can you please upload those binary and config files on Gdrive or on some other place, importing other binary and config files is not working. 

TIA

**Comment by admredbeard** [comment]
Hi, I guess you mean the HF binaries and images?

This repository is part of a thesis work and the readme is quite inextensive atm and kinda assumes you have HF up and running. I would suggest following the HF documentation and get their test network to work first if you havent. 

If you have HF test network working, what issues arise? Be sure to be in [Hyperledger/Network/](https://github.com/admredbeard/Hyperledger_Fabric_PoC/tree/main/Hyperledger/Network) folder when executing curl

**Comment by 570n3** [comment]
> 
> 
> Hi, I guess you mean the HF binaries and images?
> 
> This repository is part of a thesis work and the readme is quite inextensive atm and kinda assumes you have HF up and running. I would suggest following the HF documentation and get their test network to work first if you havent.
> 
> If you have HF test network working, what issues arise? Be sure to be in [Hyperledger/Network/](https://github.com/admredbeard/Hyperledger_Fabric_PoC/tree/main/Hyperledger/Network) folder when executing curl

I am facing this problem 
![Capture](https://user-images.githubusercontent.com/45149268/102693676-89160e00-4246-11eb-9de7-11a86e017174.PNG)
shown in the screenshot. Can you help? Please.
